### ISSUE TITLE
Output by tag like out_file (Feature Request)

### ISSUE THREAD

**Issue by btwood** [fluent/fluent-plugin-webhdfs#41]
When using the wildcard syntax, * doesn't get replaced with tag.
`/hdfs/path/to/file/*`
becomes
`/hdfs/path/to/file/*.gz`

Can this plugin be modified to behave more like out_file?

Thanks.

**Comment by tagomoris** [comment]
AFAIK, `out_file` doesn't replace `*` with tag. It replaces `*` with time_key.
This plugin supports path format using `strftime` formats. It's more useful than `*` replacing, I think. :)

Dynamic tag handling will be supported with Fluentd `v0.14`...

**Comment by btwood** [comment]
Your right. It is time. I'm not entirely sure there is a way to do it by tag natively.

I'm looking into [fluent-plugin-forest]( https://github.com/tagomoris/fluent-plugin-forest) to resolve my issue. I don't know if it's a good idea with webhdfs as the output. But I figured I'd try. The number of tags I have is not likely to exceed 200.

Thanks

**Comment by tagomoris** [comment]
I'm sure that fluent-plugin-forest works well with this plugin, because I'm the original author of both. But you should take care about buffer size limits against physical limit.
I believe that Fluentd v0.14 will solve this problem natively.

Once I'll close this issue. Please reopen this if v0.14 doesn't solve this issue.
